export const mockProblems = [
  {
    id: "REQ-" + Math.random().toString(36).substr(2, 6).toUpperCase(),
    title: "Broken Main Pipeline Spilling Potable Water",
    description: "The main water pipeline near the community center has ruptured, wasting hundreds of liters of clean water while the neighboring blocks face shortages.",
    category: "infrastructure",
    severity: "high",
    locality: "Andheri West",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    status: "in-progress",
    priority_score: 85,
    amount_needed: 5000,
    amount_raised: 1500,
    upvote_count: 42,
    ngo_id: "ngo-123",
    assigned_volunteer_id: null,
    is_public: true,
  },
  {
    id: "REQ-" + Math.random().toString(36).substr(2, 6).toUpperCase(),
    title: "Emergency Medical Supplies Shortage",
    description: "Local clinic has run out of basic first-aid kits and essential fever medication due to sudden influx of patients.",
    category: "health",
    severity: "critical",
    locality: "Dharavi",
    reportedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    status: "open",
    priority_score: 95,
    amount_needed: 10000,
    amount_raised: 8500,
    upvote_count: 120,
    ngo_id: null,
    assigned_volunteer_id: null,
    is_public: true,
  },
  {
    id: "REQ-" + Math.random().toString(36).substr(2, 6).toUpperCase(),
    title: "Food Distribution Needed After Fire",
    description: "Several families displaced by a localized fire require temporary food relief for the next 3 days.",
    category: "food",
    severity: "high",
    locality: "Mankhurd",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    status: "open",
    priority_score: 90,
    amount_needed: 15000,
    amount_raised: 0,
    upvote_count: 15,
    ngo_id: null,
    assigned_volunteer_id: null,
    is_public: true,
  },
  {
    id: "REQ-" + Math.random().toString(36).substr(2, 6).toUpperCase(),
    title: "Cleared Fallen Tree from Main Access Road",
    description: "Large tree blocked the only access road into the residential colony. Has now been cleared by local volunteers.",
    category: "infrastructure",
    severity: "critical",
    locality: "Borivali East",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    status: "resolved",
    priority_score: 80,
    amount_needed: 0,
    amount_raised: 0,
    upvote_count: 65,
    ngo_id: "ngo-123",
    assigned_volunteer_id: "vol-999",
    is_public: true,
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "REQ-" + Math.random().toString(36).substr(2, 6).toUpperCase(),
    title: "Orphaned Puppy Needs Rescue",
    description: "A small puppy is stuck in a storm drain and needs immediate extrication.",
    category: "rescue",
    severity: "medium",
    locality: "Malad West",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    status: "open",
    priority_score: 40,
    amount_needed: 0,
    amount_raised: 0,
    upvote_count: 5,
    ngo_id: "ngo-123",
    assigned_volunteer_id: null,
    is_public: true,
    is_escalated: true,
  },
  {
    id: "REQ-CLUSTER-1",
    title: "Water Contamination in Sector 4",
    description: "Drinking water appears yellowish. Immediate testing required.",
    category: "health",
    severity: "high",
    locality: "Dharavi",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    status: "open",
    priority_score: 85,
    amount_needed: 0,
    amount_raised: 0,
    upvote_count: 30,
    ngo_id: "ngo-123",
    assigned_volunteer_id: null,
    is_public: true,
    cluster_id: "cluster-dharavi-water",
  },
  {
    id: "REQ-CLUSTER-2",
    title: "Foul Odor from Sector 4 Pipes",
    description: "Strong sewage smell coming from the community taps.",
    category: "health",
    severity: "high",
    locality: "Dharavi",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    status: "open",
    priority_score: 88,
    amount_needed: 0,
    amount_raised: 0,
    upvote_count: 45,
    ngo_id: "ngo-123",
    assigned_volunteer_id: null,
    is_public: true,
    cluster_id: "cluster-dharavi-water",
  },
  {
    id: "REQ-CLUSTER-3",
    title: "Sick Children in Sector 4",
    description: "Multiple children reporting stomach aches after drinking tap water.",
    category: "health",
    severity: "critical",
    locality: "Dharavi",
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    status: "open",
    priority_score: 95,
    amount_needed: 0,
    amount_raised: 0,
    upvote_count: 110,
    ngo_id: "ngo-123",
    assigned_volunteer_id: null,
    is_public: true,
    cluster_id: "cluster-dharavi-water",
  }
];

export const mockUser = {
  id: '1',
  role: 'ngo_admin',
  name: 'Apnalaya NGO',
  email: 'admin@apnalaya.org',
  linkedProfile: {
    id: 'ngo-123',
    name: 'Apnalaya Foundation',
    locality: 'Mumbai Region'
  }
};

export const mockVolunteerProfile = {
  id: 'vol-999',
  name: 'Rahul Sharma',
  locality: 'Andheri West',
  trust_level: 'Verified',
  impact_score: 1250,
  tasks_completed: 18,
  hours_contributed: 45
};

export const mockVolunteers = [
  mockVolunteerProfile,
  {
    id: 'vol-100',
    name: 'Priya Patel',
    locality: 'Dharavi',
    trust_level: 'Verified',
    impact_score: 950,
    tasks_completed: 12,
    hours_contributed: 30
  }
];

export const mockNgoProfile = {
  id: 'ngo-123',
  name: 'Apnalaya Foundation',
  locality: 'Mumbai Region'
};
